<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="id=edge">
  <title>Inicio Template</title>
  <link rel="stylesheet" type="text/css" href="<?php echo BASE_URL; ?>/public/css/general.css" />
  <script type="text/javascript" src="<?php echo BASE_URL; ?>/public/js/jquery-3.6.0.min.js"></script>
  <script type="text/javascript" src="<?php echo BASE_URL; ?>/public/js/general.js"></script>
</head>
<body>
    <div id="header">
        <ul>
            <li><a href="<?php echo BASE_URL; ?>/inicio">Inicio</a></li>
            <li><a href="<?php echo BASE_URL; ?>/listado">Listado</a></li>
            <li><a href="<?php echo BASE_URL; ?>/resultado">Resultado</a></li>
        </ul>
    </div>
